name: CI - Build Docker

on:
  push:
    branches: [ "ramaViktor" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t demo-app .
